#docker-compose -f mysql-phpmyadmin.yml up -d

version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    volumes:
      #local dir/files: docker dir/files
      - $HOME/projects/db/mysql_db:/var/lib/mysql
      - $HOME/projects/db/mysql_db_files:/sql_files

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mysqladmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      # PMA_ARBITRARY: 1 // IF HOST is required, in case of local mysql and docker php myadmin
    # restart: always
    ports:
      - "8000:80"

volumes:
  db_data: {}
