export const STARTED_FETCHING_USER = "STARTED_FETCHING_USER"
export const STARTED_ADDING_USER = "STARTED_ADDING_USER"
export const ADDED_RESULT = "ADDED_RESULT"
export const GOT_RESULT = "GOT_RESULT"
export const GOT_ERROR = "GOT_ERROR"
export const ADDED_ERROR = "ADDED_ERROR"


export const STARTED_FETCHING_RECORD = "STARTED_FETCHING_RECORD"
export const ADD_NOTIFICATION_POPUP = "ADD_NOTIFICATION_POPUP"